In [1]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

In [2]:
print(datetime.now())

2025-02-24 08:05:29.906792

In [3]:
file_name = './Lista_operacji_20250210_114107.csv'

In [4]:
df = pd.read_csv(filepath_or_buffer='./Lista_operacji_20250210_114107.csv',sep=';')
df = pd.read_csv(file_name, nrows=10,sep=';')
# df_iter = pd.read_csv(file_name, iterator=True, chunksize=100000,sep=';')

In [5]:
df.columns = df.columns.str.replace('/', '').str.replace('  ', '_').str.replace(' ', '_').str.lower()

In [6]:
df.dtypes

data_księgowania           object
data_waluty                object
nadawca_odbiorca           object
adres_nadawcy_odbiorcy     object
rachunek_źródłowy          object
rachunek_docelowy         float64
tytułem                    object
kwota_operacji             object
waluta                     object
numer_referencyjny         object
typ_operacji               object
kategoria                  object
dtype: object

In [10]:
df['unique_row_id'] = pd.util.hash_pandas_object(df['data_księgowania'] + df['data_waluty'] + df['nadawca_odbiorca'] + 
                                                df['adres_nadawcy_odbiorcy'] + df['rachunek_źródłowy'] + df['rachunek_docelowy'] +
                                                df['tytułem'] + df['kwota_operacji'] + df['waluta'] +
                                                df['numer_referencyjny'] + df['typ_operacji'] + df['kategoria']).astype(str)

In [11]:
df['ingest_date'] = datetime.now()

In [12]:

df['data_księgowania'] = pd.to_datetime(df['data_księgowania'], format='%d.%m.%Y')
df['data_waluty'] = pd.to_datetime(df['data_waluty'], format='%d.%m.%Y')
df['kwota_operacji'] = df['kwota_operacji'].str.replace(',','.').str.replace(' ','')
df['kwota_operacji'] = pd.to_numeric(df['kwota_operacji'])

In [13]:
df.head()

,data_księgowania,data_waluty,nadawca_odbiorca,adres_nadawcy_odbiorcy,rachunek_źródłowy,rachunek_docelowy,tytułem,kwota_operacji,waluta,numer_referencyjny,typ_operacji,kategoria,unique_row_id,ingest_date
0,2025-02-10,2025-02-10,PUTKA ZAKLADOWA LODZ,NaN,'49124030281111001066432293,NaN,*********3058605,-6.96,PLN,'C992504106274045,TRANSAKCJA KARTĄ PŁATNICZĄ,Artykuły spożywcze,14733655581734590918,2025-02-24 08:07:40.122997
1,2025-02-09,2025-02-09,ALLEGRO SP. Z O.O.,"allegro.pl ul. Wierzbiecice 1B,Poznan",'49124030281111001066432293,NaN,BLIK REF 86367994064,-120.99,PLN,'C992504014038909,PŁATNOŚĆ BLIK,Zakupy przez internet,10968037546356515147,2025-02-24 08:07:40.122997
2,2025-02-08,2025-02-07,Dodatek do P*TK1P53PY4 primevideo.pl LUX,NaN,'5267********3604,NaN,NaN,-24.99,PLN,'52715615038204559563263,ZAKUP,Multimedia,6422017928252083068,2025-02-24 08:07:40.122997
3,2025-02-08,2025-02-08,JMP S.A. BIEDRONKA 108 LODZ,NaN,'49124030281111001066432293,NaN,*********3058605,-121.61,PLN,'C992503914694915,TRANSAKCJA KARTĄ PŁATNICZĄ,Artykuły spożywcze,5660805638982890358,2025-02-24 08:07:40.122997
4,2025-02-08,2025-02-08,WINTEA SP. z o.o. Lodz,NaN,'49124030281111001066432293,NaN,*********3058605,-27.50,PLN,'C992503914743938,TRANSAKCJA KARTĄ PŁATNICZĄ,Alkohol,201604162485306458,2025-02-24 08:07:40.122997

In [14]:
engine = create_engine('postgresql://kestra:k3str4@localhost:5432/dev')

In [15]:
print(pd.io.sql.get_schema(df, name='posting', con=engine))

CREATE TABLE posting (
	"data_księgowania" TIMESTAMP WITHOUT TIME ZONE,
	data_waluty TIMESTAMP WITHOUT TIME ZONE,
	nadawca_odbiorca TEXT,
	adres_nadawcy_odbiorcy TEXT,
	"rachunek_źródłowy" TEXT,
	rachunek_docelowy FLOAT(53),
	"tytułem" TEXT,
	kwota_operacji FLOAT(53),
	waluta TEXT,
	numer_referencyjny TEXT,
	typ_operacji TEXT,
	kategoria TEXT,
	unique_row_id TEXT,
	ingest_date TIMESTAMP WITHOUT TIME ZONE
)

In [16]:
df.head(n=0)

Empty DataFrame
Columns: [data_księgowania, data_waluty, nadawca_odbiorca, adres_nadawcy_odbiorcy, rachunek_źródłowy, rachunek_docelowy, tytułem, kwota_operacji, waluta, numer_referencyjny, typ_operacji, kategoria, unique_row_id, ingest_date]
Index: []

In [19]:
df.head(n=0).to_sql(name='stg_posting', con=engine, if_exists='replace',schema='raw',index=False)

0

In [20]:
df.to_sql(name='stg_posting', con=engine, if_exists='replace',schema='raw')

10